services:
  node:
    ports:
      - 3000:3000
    networks:
      - default
      - backend
  redis-insight:
    ports:
      - "5540:5540"

networks:
  backend:
    name: booxit-backend_web-server-network
    external: true