<template>
  <div
    class="relative rounded-3xl bg-linear-to-br from-primary to-violet-700 overflow-hidden items-center justify-center p-4 min-h-80"
    aria-hidden="true"
  >
    <div class="absolute top-0 right-0 w-56 h-56 rounded-full bg-white/5 -translate-y-1/2 translate-x-1/2" />
    <div class="absolute bottom-0 left-0 w-44 h-44 rounded-full bg-white/5 translate-y-1/2 -translate-x-1/2" />
    <div class="absolute inset-0 bg-linear-to-t from-black/10 to-transparent" />
    <svg
      viewBox="0 0 360 300"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      class="relative z-10 w-full max-w-sm"
    >
      <circle
        cx="180"
        cy="150"
        r="130"
        fill="white"
        fill-opacity="0.04"
      />
      <rect
        x="110"
        y="18"
        width="140"
        height="244"
        rx="22"
        fill="white"
        fill-opacity="0.12"
        stroke="white"
        stroke-width="1.5"
        stroke-opacity="0.25"
      />
      <rect
        x="120"
        y="52"
        width="120"
        height="180"
        rx="6"
        fill="white"
        fill-opacity="0.07"
      />
      <rect
        x="120"
        y="52"
        width="120"
        height="38"
        rx="6"
        fill="white"
        fill-opacity="0.22"
      />
      <rect
        x="120"
        y="78"
        width="120"
        height="12"
        fill="white"
        fill-opacity="0.22"
      />
      <rect
        x="134"
        y="64"
        width="52"
        height="9"
        rx="4.5"
        fill="white"
        fill-opacity="0.8"
      />
      <rect
        x="196"
        y="64"
        width="14"
        height="9"
        rx="4.5"
        fill="white"
        fill-opacity="0.35"
      />
      <rect
        x="215"
        y="64"
        width="14"
        height="9"
        rx="4.5"
        fill="white"
        fill-opacity="0.35"
      />
      <circle
        cx="142"
        cy="106"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="162"
        cy="106"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="182"
        cy="106"
        r="9"
        fill="white"
        fill-opacity="0.7"
      />
      <circle
        cx="202"
        cy="106"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="222"
        cy="106"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="142"
        cy="127"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="162"
        cy="127"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="182"
        cy="127"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="202"
        cy="127"
        r="9"
        fill="white"
        fill-opacity="0.45"
      />
      <circle
        cx="222"
        cy="127"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="142"
        cy="148"
        r="9"
        fill="white"
        fill-opacity="0.45"
      />
      <circle
        cx="162"
        cy="148"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="182"
        cy="148"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="202"
        cy="148"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <circle
        cx="222"
        cy="148"
        r="9"
        fill="white"
        fill-opacity="0.15"
      />
      <rect
        x="126"
        y="163"
        width="108"
        height="56"
        rx="9"
        fill="white"
        fill-opacity="0.12"
        stroke="white"
        stroke-width="1"
        stroke-opacity="0.2"
      />
      <rect
        x="126"
        y="167"
        width="5"
        height="48"
        rx="2.5"
        fill="white"
        fill-opacity="0.8"
      />
      <rect
        x="138"
        y="173"
        width="62"
        height="7"
        rx="3.5"
        fill="white"
        fill-opacity="0.7"
      />
      <rect
        x="138"
        y="185"
        width="42"
        height="5"
        rx="2.5"
        fill="white"
        fill-opacity="0.45"
      />
      <rect
        x="138"
        y="195"
        width="52"
        height="5"
        rx="2.5"
        fill="white"
        fill-opacity="0.35"
      />
      <circle
        cx="258"
        cy="62"
        r="26"
        fill="#10b981"
      />
      <path
        d="M247 62 L255 70 L270 53"
        stroke="white"
        stroke-width="3.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <rect
        x="52"
        y="150"
        width="92"
        height="46"
        rx="12"
        fill="white"
        fill-opacity="0.12"
        stroke="white"
        stroke-width="1"
        stroke-opacity="0.2"
      />
      <circle
        cx="74"
        cy="173"
        r="12"
        fill="white"
        fill-opacity="0.2"
      />
      <rect
        x="68"
        y="168"
        width="12"
        height="10"
        rx="2"
        fill="white"
        fill-opacity="0.55"
      />
      <rect
        x="93"
        y="165"
        width="38"
        height="6"
        rx="3"
        fill="white"
        fill-opacity="0.5"
      />
      <rect
        x="93"
        y="175"
        width="26"
        height="5"
        rx="2.5"
        fill="white"
        fill-opacity="0.4"
      />
    </svg>
  </div>
</template>
