import { z } from 'zod'

type Category = { text: string, value: string, icon: string, bgCls: string, iconCls: string }

export const categories = [
  {
    text: 'schemas.services.category.entry.Hairdresser',
    value: 'Hairdresser',
    icon: 'icon-park-outline:hair-brush',
    bgCls: 'bg-purple-500/15',
    iconCls: 'text-purple-600 dark:text-purple-400',
  },
  {
    text: 'schemas.services.category.entry.Barber',
    value: 'Barber',
    icon: 'icon-park-outline:english-mustache',
    bgCls: 'bg-blue-500/15',
    iconCls: 'text-blue-600 dark:text-blue-400',
  },
  {
    text: 'schemas.services.category.entry.Skin_Care_&_Spa',
    value: 'Skin Care & Spa',
    icon: 'icon-park-outline:lotus',
    bgCls: 'bg-rose-500/15',
    iconCls: 'text-rose-600 dark:text-rose-400',
  },
  {
    text: 'schemas.services.category.entry.Nails',
    value: 'Nails',
    icon: 'icon-park-outline:fingernail',
    bgCls: 'bg-pink-500/15',
    iconCls: 'text-pink-600 dark:text-pink-400',
  },
  {
    text: 'schemas.services.category.entry.Brows_&_Lashes',
    value: 'Brows & Lashes',
    icon: 'icon-park-outline:eyebrow',
    bgCls: 'bg-violet-500/15',
    iconCls: 'text-violet-600 dark:text-violet-400',
  },
  {
    text: 'schemas.services.category.entry.Cosmetic_Treatments',
    value: 'Cosmetic Treatments',
    icon: 'icon-park-outline:cosmetic-brush',
    bgCls: 'bg-fuchsia-500/15',
    iconCls: 'text-fuchsia-600 dark:text-fuchsia-400',
  },
  {
    text: 'schemas.services.category.entry.Wellness',
    value: 'Wellness',
    icon: 'icon-park-outline:sleaves',
    bgCls: 'bg-teal-500/15',
    iconCls: 'text-teal-600 dark:text-teal-400',
  },
  {
    text: 'schemas.services.category.entry.Healthcare',
    value: 'Healthcare',
    icon: 'icon-park-outline:medicine-chest',
    bgCls: 'bg-red-500/15',
    iconCls: 'text-red-600 dark:text-red-400',
  },
  {
    text: 'schemas.services.category.entry.Fitness_&_Sports',
    value: 'Fitness & Sports',
    icon: 'icon-park-outline:fitness',
    bgCls: 'bg-yellow-500/15',
    iconCls: 'text-yellow-600 dark:text-yellow-400',
  },
  {
    text: 'schemas.services.category.entry.Sports_Facilities_Rental',
    value: 'Sports Facilities Rental',
    icon: 'icon-park-outline:golf-course',
    bgCls: 'bg-green-500/15',
    iconCls: 'text-green-600 dark:text-green-400',
  },
  {
    text: 'schemas.services.category.entry.Accommodation',
    value: 'Accommodation',
    icon: 'icon-park-outline:hotel',
    bgCls: 'bg-indigo-500/15',
    iconCls: 'text-indigo-600 dark:text-indigo-400',
  },
  {
    text: 'schemas.services.category.entry.Rentals',
    value: 'Rentals',
    icon: 'icon-park-outline:car',
    bgCls: 'bg-amber-500/15',
    iconCls: 'text-amber-600 dark:text-amber-400',
  },
  {
    text: 'schemas.services.category.entry.Travel',
    value: 'Travel',
    icon: 'icon-park-outline:coconut-tree',
    bgCls: 'bg-sky-500/15',
    iconCls: 'text-sky-600 dark:text-sky-400',
  },
  {
    text: 'schemas.services.category.entry.Restaurants',
    value: 'Restaurants',
    icon: 'icon-park-outline:chef-hat-one',
    bgCls: 'bg-green-500/15',
    iconCls: 'text-green-600 dark:text-green-400',
  },
  {
    text: 'schemas.services.category.entry.Catering',
    value: 'Catering',
    icon: 'icon-park-outline:fork-spoon',
    bgCls: 'bg-yellow-500/15',
    iconCls: 'text-yellow-600 dark:text-yellow-400',
  },
  {
    text: 'schemas.services.category.entry.Cleaning',
    value: 'Cleaning',
    icon: 'icon-park-outline:vacuum-cleaner',
    bgCls: 'bg-cyan-500/15',
    iconCls: 'text-cyan-600 dark:text-cyan-400',
  },
  {
    text: 'schemas.services.category.entry.Home_Maintenance',
    value: 'Home Maintenance',
    icon: 'icon-park-outline:home',
    bgCls: 'bg-amber-500/15',
    iconCls: 'text-amber-600 dark:text-amber-400',
  },
  {
    text: 'schemas.services.category.entry.Facilities_Rental',
    value: 'Facilities Rental',
    icon: 'icon-park-outline:building-four',
    bgCls: 'bg-stone-500/15',
    iconCls: 'text-stone-600 dark:text-stone-400',
  },
  {
    text: 'schemas.services.category.entry.Education',
    value: 'Education',
    icon: 'icon-park-outline:bachelor-cap',
    bgCls: 'bg-blue-500/15',
    iconCls: 'text-blue-600 dark:text-blue-400',
  },
  {
    text: 'schemas.services.category.entry.Automotive',
    value: 'Automotive',
    icon: 'icon-park-outline:tool',
    bgCls: 'bg-slate-500/15',
    iconCls: 'text-slate-600 dark:text-slate-400',
  },
  {
    text: 'schemas.services.category.entry.Finance',
    value: 'Finance',
    icon: 'icon-park-outline:wallet',
    bgCls: 'bg-emerald-500/15',
    iconCls: 'text-emerald-600 dark:text-emerald-400',
  },
  {
    text: 'schemas.services.category.entry.Legal',
    value: 'Legal',
    icon: 'icon-park-outline:gavel',
    bgCls: 'bg-yellow-500/15',
    iconCls: 'text-yellow-600 dark:text-yellow-400',
  },
  {
    text: 'schemas.services.category.entry.Business',
    value: 'Business',
    icon: 'icon-park-outline:briefcase',
    bgCls: 'bg-sky-500/15',
    iconCls: 'text-sky-600 dark:text-sky-400',
  },
  {
    text: 'schemas.services.category.entry.Pet_Care',
    value: 'Pet Care',
    icon: 'icon-park-outline:cat',
    bgCls: 'bg-lime-500/15',
    iconCls: 'text-lime-600 dark:text-lime-400',
  },
  {
    text: 'schemas.services.category.entry.Tech_support',
    value: 'Tech support',
    icon: 'icon-park-outline:monitor-one',
    bgCls: 'bg-cyan-500/15',
    iconCls: 'text-cyan-600 dark:text-cyan-400',
  },
  {
    text: 'schemas.services.category.entry.Other',
    value: 'Other',
    icon: 'icon-park-outline:other',
    bgCls: 'bg-neutral-500/15',
    iconCls: 'text-neutral-600 dark:text-neutral-400',
  },
] satisfies Category[]

export const values = categories.map(entry => entry.value)

export default z.enum(values)
